### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pixel-xd** [IDKFORCE/fs-serversidegraphics#1]
Question

Is there any way to change NPC cars to addons..?

**Comment by novahaxor** [comment]
yea i gotchu homie, https://github.com/LeoGillet/trafficaddon
use that along with the popgroups file from your gta5, be sure to save as xml, if you need extra help lmk with a discord

**Comment by pixel-xd** [comment]
> yea i gotchu homie, https://github.com/LeoGillet/trafficaddon use that along with the popgroups file from your gta5, be sure to save as xml, if you need extra help lmk with a discord

Ok ill try this **thanks for ur help**
