### ISSUE TITLE
cars

### ISSUE THREAD

**Issue by jrichards9393** [IDKFORCE/fs-serversidegraphics#5]
makes car radios way brighter than they are supposed to be. like a sun glare from the car radio

**Comment by IDKFORCE** [comment]
for now delete [visualsettings.dat](https://github.com/IDKFORCE/fs-serversidegraphics/blob/main/visualsettings.dat) update is coming soon so make sure you join the discord since there alot coming
https://discord.com/invite/UFng7DWnWP
