### ISSUE TITLE
lights way too bright in places 

### ISSUE THREAD

**Issue by sabotage93thctv** [IDKFORCE/fs-serversidegraphics#6]
the lights at places like vehicle lights are way to bright ie a blinding effect any way i can turn just the lights off for this as some cars are glowing inside lol

**Comment by sabotage93thctv** [comment]
the sun also has a super blinding effect in the day its a bit too much lol

**Comment by IDKFORCE** [comment]
for now delete [visualsettings.dat](https://github.com/IDKFORCE/fs-serversidegraphics/blob/main/visualsettings.dat)

**Comment by IDKFORCE** [comment]
update is coming soon so make sure you join the discord since there alot coming
https://discord.com/invite/UFng7DWnWP

**Comment by sabotage93thctv** [comment]
done that and still no changes bud
