### ISSUE TITLE
lights stilll too bright after deleting visual.dat

### ISSUE THREAD

**Issue by sabotage93thctv** [IDKFORCE/fs-serversidegraphics#7]
we deleted the file as suggested and its still bad worse at a night time
![Screenshot 2024-07-29 214131](https://github.com/user-attachments/assets/563f9e4d-def1-4cce-a778-794b5f2df3be)
some mlos seems to make the issue worse but even standard gta areas do it

**Comment by sabotage93thctv** [comment]
any help lool :)

**Comment by IDKFORCE** [comment]
i been working on v2 for now just take out visualsettings.dat

**Comment by sabotage93thctv** [comment]
We have lol Thankyou
Sent from my iPhone

On 7 Aug 2024, at 07:54, GhostFace Scripts ***@***.***> wrote:

﻿

i been working on v2 for now just take out visualsettings.dat

**Comment by sabotage93thctv** [comment]
any advice as we have been waiting a min and same problem after we removed the file bud :L day looks perfect night time some places look ass almost all blurr
